### ISSUE TITLE
yadcf + colreorder + server side : problem with the selected value with select filter

### ISSUE THREAD

**Issue by johndegey** [vedmack/yadcf#150] opened 2015-01-22 15:42 UTC
Hello,

I've got a problem, not sure it as been reported.
I'm using the 0.8.7b9 with the new version of datatable.

First, it still have the focus problem when the filters are in the header. I've changed to the footer, and then the focus works.

Second, i was using the "data" parameter for my select filter in the initialization of yadcf.
But then, when i switch col2 and col3 (each has a select filter), then go to the next page, the filter is then reapply but as if i did not change the column order.
=> wrong filter for the col2 and col3

Third, i've change my initialization and remove the data parameter for all the select filter.
The values are returned by the xhr request in the json response : yadcf_data_2 and yadcf_data_3.
My code set the good  values for the right column, so the col2 and col3 have the right select filter.

But now, the filter have not the selected option set as it should be.
It seems that the original column number is used instead of the new one.

Thx for you're work. 

Edit : it seems to appear only if there is a column with a select filter between the new and the original position of the column that you're moving (with a select filter too)

**Comment by vedmack** [comment] 2015-01-22 22:45
The first issue is fixed in the latest version (see https://github.com/vedmack/yadcf/issues/123)

Beside that the ColReorder is not fully supported yet, see https://github.com/vedmack/yadcf/issues/138, so I'll close this on because its might be a duplicate of https://github.com/vedmack/yadcf/issues/138 , if after the fix of the https://github.com/vedmack/yadcf/issues/138 you will still have problems feel free to open new issue

**Closed by vedmack** 2015-01-22 22:45 UTC
