### ISSUE TITLE
exFilterColumn: Uncaught TypeError: Cannot assign to read only property '0' of string

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#404] opened 2017-05-17 13:20 UTC
I'm getting this error in the console when trying to set a default value.
Uncaught TypeError: Cannot assign to read only property '0' of string 'Yes'
I have tried with different column (datat-type text) and I'm having the same error.
I'm using this code
```
yadcf.init(table18, [
						
						{column_number : 4, // Active 
							filter_container_id: 'divisions_4',
							filter_type: "multi_select",
							select_type: 'select2',
							select_type_options: {
								width:'100%',
								language: "<?php echo ASLang::getLanguage(); ?>",
								allowClear: true 
							}, 
							filter_default_label: placeholder, // multi-select
							column_data_type: "html",
							html_data_type: "text",
							filter_reset_button_text: false // hide yadcf reset button
					
						},
							
					],
					{cumulative_filtering: false},
					{externally_triggered: true});  
					
					yadcf.exFilterColumn(table18, [
						
						[4, "Yes"]
					]);
```

**Comment by vedmack** [comment] 2017-05-24 10:12
Please provide a test page in which your issue is reproduced...

**Comment by lenamtl** [comment] 2017-05-24 14:59
Hi,
Here is a jsfiddle to see the errors I'm having.
https://jsfiddle.net/lenamtl/x798d99g/1/

What I d'like to do :
1- is filter some value by default
2- other case display no value by default in the entire table and only show the row if I do a search using Yadcf filters

**Comment by vedmack** [comment] 2017-05-29 07:31
looks like a bug related to multi select and exFilterColumn , will see what went wrong

**Comment by lenamtl** [comment] 2017-05-29 15:53
ok thanks

**Comment by lenamtl** [comment] 2017-06-09 12:20
Any news on how to fix this?

Thanks

**Comment by vedmack** [comment] 2017-06-09 14:20
fixed in [0.9.2.beta.12](https://github.com/vedmack/yadcf/blob/63e161ef2d3b441eeba960399ae3b365234c4f78/src/jquery.dataTables.yadcf.js)

**Closed** 2017-06-09 14:19 UTC
Labels: bug

**Comment by vedmack** [comment] 2017-06-09 14:24
here is a working [jsfiddle ](https://jsfiddle.net/vedmack/x798d99g/8/)- use select2 v4 full 

as to the "2- other case display no value by default in the entire table and only show the row if I do a search using Yadcf filters" , see how you can do it with datatables and then try to use yadcf for better filtering, you can post a question on stackoverflow if you want

**Comment by lenamtl** [comment] 2017-06-09 14:29
Ok thanks for the fix and additional info.
I will do some tests

**Comment by lenamtl** [comment] 2017-10-31 14:47
Do you mind telling me which line of code is related to this fix thanks
