### ISSUE TITLE
Filter not being applied anymore after reordering columns

### ISSUE THREAD

**Issue by Cymo-** [vedmack/yadcf#199] opened 2015-05-21 09:43 UTC
Hello,

I still have the problem even with the **latest beta** (using **0.8.8.beta.30** in local, and 0.8.8.beta.26 in jsfiddle) that is supposed to handle reordering on all filter types.

Here is my code example :
http://jsfiddle.net/Cymo_/j7h7c5cg/11/

The col 3 is supposed to be filtered by the number range slider, and the col 0 by the multiple select.
It work fine with the "All" and "Scenario 1" scenarios because the order is the same. 
But when I manually reorder or when I chose another scenario, suddenly, a wild bug appears and is super effective (aka the filters don't work anymore)!

I am using external filters and I select the content to filter with the "html_data_selector" property.

Any ideas?
Thanks for your help!
Tim

**Comment by vedmack** [comment] 2015-05-21 10:30
Please try [beta.31](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/resources/js/jquery.dataTables.yadcf.js)

**Comment by Cymo-** [comment] 2015-05-21 15:38
Hi vedmack,

It seems like it does not work either with the beta.31 version of the script. :(

Here is the jsfiddle : http://jsfiddle.net/j7h7c5cg/13/
You can see in the 'External Resources' section that I included the file you linked in your last comment.

Am I doing something wrong?

**Comment by johndegey** [comment] 2015-05-21 16:18
Hello Daniel,

I confirm this problem with beta 32 too (see all my test case).
http://yadcf.johndegey.org/

**Comment by vedmack** [comment] 2015-05-21 21:02
Will see what went wrong, because I remember it used to work in your examples @johndegey

**Comment by vedmack** [comment] 2015-05-22 20:10
can you check your table with the [beta.17](https://raw.githubusercontent.com/vedmack/yadcf/3579f3f0291327eed2b5e164c59d1a6d5ba1f942/lab/jquery.dataTables.yadcf.js) version and tell me how it works for you

**Comment by vedmack** [comment] 2015-05-25 10:26
closing this one because I found the bug that messed my colreorder suppport, hopefully it fixed your issue too, if not let me know,

grab the [beta.35](https://github.com/vedmack/yadcf/blob/218b6071bcdc216e6e8cc617dedf436035c2a821/beta/jquery.dataTables.yadcf.js)

**Closed by vedmack** 2015-05-25 10:26 UTC

**Comment by Cymo-** [comment] 2015-05-26 08:31
Seems to work fine with the beta.35, awesome work man.

I will get back to you if I find some side effects of your bugfix.

Again, thank you ! :)

**Comment by johndegey** [comment] 2015-05-26 12:10
Nice work...
Thanks

**Comment by Cymo-** [comment] 2015-05-26 13:19
Hi Daniel,

Datatables forgets the pagination and the filters that have been set with "exFilterColumn" when I refreshthe page... (The filters set through the UI are saved)
Could it be related?

Might be a problem similar to the one you posted in february : 
https://github.com/DataTables/DataTables/issues/499

I use table.columns.adjust().draw(false); myself at some point (note the boolean), but it does not work either.

I tried with the nightly 1.10.8-dev of Datatables and the last beta of your plugin (beta.35).

Thanks!

**Comment by vedmack** [comment] 2015-05-26 18:54
Hi,

Try without yadcf, and see if pagination getting lost after refresh, also try with `.draw(true)` ... if it works with `true` report to datatables, if pagination getting lost in either true or false report to datatables too

**Comment by Cymo-** [comment] 2015-05-28 09:33
Hi,

I did try without yadcf, it works as expected : 
DataTables saves the pagination and the draw(true) resets it (draw(false) does not change the current pagination as well)

I got two questions remaining : 
- Is it normal that the filters are not saved with ``oTable.fnSettings().oApi._fnSaveState(oTable.fnSettings());`` when calling the ``exFilterColumn`` method?
I see in the ``exFilterColumn`` method that the ``oTable.fnSettings().oLoadedState.yadcfState``
array is not updated when setting programmaticaly the column filter value.
Would it be possible to do so when the stateSave parameter is set to true in the DataTables settings?
I don't know if it is a bug or a feature. :)

- For the pagination loss problem :
The ``oTable.fnDraw(false);`` in the ``initAndBindTable`` function on line 2995 is the one responsible of the pagination change (commented it, the pagination did not change on page refresh).
Though, the fnDraw() is supposed to be fixed in the version of DT that I use...
Do you think it is a problem on the DT side?

Thanks for you help / work !

**Comment by vedmack** [comment] 2015-05-28 19:19
Thanks, I will check it in the following days

**Comment by vedmack** [comment] 2015-05-29 21:12
grab beta.36 it solves the StateSavefor exFilterColumn , as to the pagination, I could not reproduce it, try this [link](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_source.html) , you can try calling `yadcf.exFilterColumn(oTable, [[4, 'Tag1']]);` from the dev tools console, the best thing would be if you provide a link to a working sample with a scenario to reproduce it... (better open a new issue for that)

**Comment by DiloWagner** [comment] 2016-09-04 18:33
Hi vedmack,

I have the same problem with pagination. The @Cymo had previously reported.

I am using the DataTables version 1.10.12 and Yadcf version 0.8.9.

I am using stateSave: true and when i go refresh the page, my pagination not save.

When i changed the code at line 3413:

```javascript
//when using DOM source
if (isDOMSource(oTable)) {
	//we need to make sure that the yadcf state will be saved after page reload
	oTable.fnSettings().oApi._fnSaveState(oTable.fnSettings());
	//redraw the table in order to apply the filters
	oTable.fnDraw(false);
}
```
to:

```javascript
//when using DOM source
if (isDOMSource(oTable)) {
	//we need to make sure that the yadcf state will be saved after page reload
	oTable.fnSettings().oApi._fnSaveState(oTable.fnSettings());
	//redraw the table in order to apply the filters
	oTable.draw(true); // ** I changed **
}
```
It's works!

Your link previously reported is broken.
You can check, please?

Thank you.

**Comment by vedmack** [comment] 2016-09-04 19:13
Hi,

Please provide a test page using your prefered js playground page with the latest datatables and the latest yadcf beta and open a new issue

**Comment by DiloWagner** [comment] 2016-09-04 23:20
Ok, thank you!

I will provide
