### ISSUE TITLE
option to disable the sorting on the filter.

### ISSUE THREAD

**Issue by MHL3060** [vedmack/yadcf#237] opened 2015-09-17 16:34 UTC
Currently for the text search filter, if you enter some text and hit enter, it does two things.

1). it filters the data based on the entered text.
2). it sort by this column. 

It looks like only for the text search filter. other filter seems preserve the sorting column position.

to reproduce.

go to http://yadcf-showcase.appspot.com/DOM_source.html

1). click "Customer" column so it sort the customer column alphabetically.
2). enter "a_values" into "Values" search box and hit enter.
3). now the sorting is based on the "Values" column instead of my original column "Customer"

This behaviour doesn't observe for the drop down filter or other filters.

it would be nice to provide an option to disable the sorting the column by hitting the enter.

**Comment by vedmack** [comment] 2015-09-17 17:07
duplicate of https://github.com/vedmack/yadcf/issues/233 (funny that this two issues were opened almost one after the other)

**Closed by vedmack** 2015-09-17 17:07 UTC
Labels: duplicate
