### ISSUE TITLE
Reset button with icon instead of text not working for range filters

### ISSUE THREAD

**Issue by misanek** [vedmack/yadcf#543] opened 2019-02-07 11:58 UTC
Hi,
found bug, here is a jsFiddle with example: http://jsfiddle.net/fp2q4bex/2/

for text filters it works fine, but when you click on a icon and not on the button in range filters it doesn't work.

**Comment by vedmack** [comment] 2019-02-07 12:29
Hhhhh @misanek  and @konuch you both work at the same place?
`filter_reset_button_text` was meant for plain text only, so that not a bug but rather a feature, but that doesn't mean that I wont add support for it 😜

**Comment by konuch** [comment] 2019-02-07 12:56
Hey Daniel, thanks, it will be really appreciated. And yes, you've guessed it, we're colleagues :)

**Comment by vedmack** [comment] 2019-02-07 14:43
fixed by @misanek in PR https://github.com/vedmack/yadcf/pull/544

**Closed by vedmack** 2019-02-07 14:43 UTC
Labels: enhancement
